"""e3cli setup — interactive setup wizard."""

from __future__ import annotations

import getpass
import os
import shutil
from pathlib import Path

import typer
from rich.console import Console
from rich.panel import Panel
from rich.text import Text

from e3cli import __version__
from e3cli.auth import AuthError, get_token
from e3cli.config import CONFIG_DIR, CONFIG_FILE, ensure_dirs, save_token
from e3cli.credential import list_profiles, save_credentials, save_profile_meta, save_token_for_profile
from e3cli.i18n import set_lang, t

console = Console()
app = typer.Typer()

BANNER = r"""
    _____ ____   _____ _      _____
   / ____|___ \ / ____| |    |_   _|
  | |__    __) | |    | |      | |
  |  __|  |__ <| |    | |      | |
  | |____ ___) | |____| |____ _| |_
  |______|____/ \_____|______|_____|
"""


def is_first_run() -> bool:
    return not CONFIG_FILE.exists()


def _choose_language() -> str:
    console.print("[bold cyan]Language / 語言[/bold cyan]")
    console.print("  [cyan]1[/cyan] 繁體中文")
    console.print("  [cyan]2[/cyan] English")
    choice = typer.prompt("Choose / 請選擇", default="1", show_default=True)
    if choice.strip() in ("2", "en", "EN", "english", "English"):
        return "en"
    return "zh"


def _choose_semester_format(lang: str) -> str:
    if lang == "zh":
        console.print("[bold cyan]學期格式[/bold cyan]")
        console.print("[dim]用於辨識課程所屬學期，預設只同步/下載當期課程[/dim]")
        console.print("  [cyan]1[/cyan] NYCU / 台灣大學 (前4碼: 1142 = 114學年第2學期) [預設]")
        console.print("  [cyan]2[/cyan] 西曆年制 (前4碼: 2025)")
        console.print("  [cyan]3[/cyan] 不解析 (所有課程視為當期)")
    else:
        console.print("[bold cyan]Semester format[/bold cyan]")
        console.print("[dim]Used to detect current semester. Only current semester is synced by default.[/dim]")
        console.print("  [cyan]1[/cyan] NYCU / Taiwan universities (prefix 4 digits: 1142 = year 114 sem 2) [default]")
        console.print("  [cyan]2[/cyan] Western year (prefix 4 digits: 2025)")
        console.print("  [cyan]3[/cyan] None (treat all courses as current)")

    choice = typer.prompt("", default="1", show_default=False)
    if choice.strip() == "2":
        return "western"
    if choice.strip() == "3":
        return "none"
    return "nycu"


def _setup_alias(lang: str) -> str:
    if lang == "zh":
        console.print("[bold cyan]指令別名 (Alias)[/bold cyan]")
        console.print(Panel(
            "設定一個自訂指令名稱，讓你可以用自己喜歡的名字呼叫此工具。\n"
            "例如設定 [cyan]moodle[/cyan]，之後就可以用 [cyan]moodle courses[/cyan] 代替 [cyan]e3cli courses[/cyan]。\n"
            "用法完全相同，只是名字不同。留空則不設定。",
            border_style="dim",
        ))
    else:
        console.print("[bold cyan]Command Alias[/bold cyan]")
        console.print(Panel(
            "Set a custom command name so you can call this tool with your preferred name.\n"
            "For example, set [cyan]moodle[/cyan] to use [cyan]moodle courses[/cyan] instead of [cyan]e3cli courses[/cyan].\n"
            "Same usage, just a different name. Leave empty to skip.",
            border_style="dim",
        ))

    alias = typer.prompt("Alias", default="", show_default=False)
    alias = alias.strip()

    if alias:
        _install_alias(alias)
    return alias


def _install_alias(alias: str) -> None:
    """建立 alias 腳本並自動寫入 shell profile。"""
    e3cli_path = shutil.which("e3cli")
    if not e3cli_path:
        e3cli_path = "e3cli"

    bin_dir = CONFIG_DIR / "bin"
    bin_dir.mkdir(exist_ok=True)
    alias_path = bin_dir / alias

    alias_path.write_text(f"""#!/usr/bin/env bash
# e3cli alias: {alias} → e3cli
# Auto-generated by e3cli setup. Delete to remove.
exec {e3cli_path} "$@"
""")
    alias_path.chmod(0o755)

    # 自動寫入 shell profile
    bin_str = str(bin_dir)
    export_line = f'export PATH="{bin_str}:$PATH"'
    marker = "# e3cli alias PATH"

    profile = _detect_shell_profile()
    if profile:
        existing = profile.read_text() if profile.exists() else ""
        if marker not in existing:
            with open(profile, "a") as f:
                f.write(f"\n{export_line}  {marker}\n")
            console.print(f"[green]  ✓ {alias} → e3cli[/green]")
            console.print(f"[green]  ✓ PATH 已自動寫入 {profile}[/green]")
            console.print(f"[dim]  重開終端或執行 source {profile} 即可使用[/dim]")
        else:
            console.print(f"[green]  ✓ {alias} → e3cli (PATH 已設定)[/green]")
    else:
        console.print(f"[green]  ✓ {alias} → e3cli[/green]")
        console.print(f"[dim]  請手動加入: {export_line}[/dim]")


def _detect_shell_profile() -> Path | None:
    """偵測當前 shell 的 profile 檔案。"""
    home = Path.home()
    shell = os.environ.get("SHELL", "")

    if "zsh" in shell:
        return home / ".zshrc"
    if "bash" in shell:
        # macOS 用 .bash_profile, Linux 用 .bashrc
        bash_profile = home / ".bash_profile"
        bashrc = home / ".bashrc"
        if bash_profile.exists():
            return bash_profile
        return bashrc
    if "fish" in shell:
        conf = home / ".config" / "fish" / "config.fish"
        conf.parent.mkdir(parents=True, exist_ok=True)
        return conf

    # fallback: 看哪個存在
    for candidate in [home / ".zshrc", home / ".bashrc", home / ".bash_profile"]:
        if candidate.exists():
            return candidate
    return None


def run_setup_wizard() -> None:
    console.print()
    console.print(Panel(
        Text(BANNER, style="cyan", justify="center"),
        title=f"[bold]Welcome to e3cli v{__version__}[/bold]",
        subtitle="Moodle automation tool",
        border_style="cyan",
    ))
    console.print()

    # Step 0: Language
    lang = _choose_language()
    set_lang(lang)
    console.print()

    console.print(f"[bold]{t('setup.welcome')}[/bold]")
    console.print()

    # Step 1: Moodle URL
    console.print(f"[bold cyan]Step 1/5[/bold cyan] — {t('setup.step_url')}")
    if lang == "zh":
        console.print("[dim]輸入你的 Moodle 網址。支援任何學校的 Moodle 平台。[/dim]")
    else:
        console.print("[dim]Enter your Moodle URL. Any school's Moodle platform is supported.[/dim]")
    url = typer.prompt(
        "Moodle URL",
        default="https://e3p.nycu.edu.tw",
        show_default=True,
    ).rstrip("/")
    console.print()

    # Step 2: Semester format
    console.print("[bold cyan]Step 2/5[/bold cyan] — ", end="")
    sem_format = _choose_semester_format(lang)
    console.print()

    # Step 3: Download directory
    console.print(f"[bold cyan]Step 3/5[/bold cyan] — {t('setup.step_dir')}")
    console.print(f"[dim]{t('setup.step_dir_hint')}[/dim]")
    default_dir = os.path.expanduser("~/e3-downloads")
    download_dir = typer.prompt(
        t("setup.step_dir"),
        default=default_dir,
        show_default=True,
    )
    console.print()

    # Step 4: Alias
    console.print("[bold cyan]Step 4/5[/bold cyan] — ", end="")
    alias = _setup_alias(lang)
    console.print()

    # Save config
    ensure_dirs()
    config_content = f"""[moodle]
url = "{url}"
service = "moodle_mobile_app"

[storage]
download_dir = "{download_dir}"

[schedule]
interval_minutes = 60
notify = true

[general]
lang = "{lang}"
semester_format = "{sem_format}"
alias = "{alias}"
"""
    CONFIG_FILE.write_text(config_content)
    console.print(f"[green]  {t('setup.config_saved', path=CONFIG_FILE)}[/green]")
    console.print()

    # Step 5: Login
    console.print(f"[bold cyan]Step 5/5[/bold cyan] — {t('setup.step_login')}")
    want_login = typer.confirm(t("setup.want_login"), default=True)

    if want_login:
        # 詢問 profile 名稱
        existing = list_profiles()
        if existing:
            names = ", ".join(p["name"] for p in existing)
            if lang == "zh":
                console.print(f"[dim]  已有帳號: {names}[/dim]")
                console.print("[dim]  輸入新名稱建立新帳號，或輸入已有名稱覆蓋[/dim]")
            else:
                console.print(f"[dim]  Existing profiles: {names}[/dim]")
                console.print("[dim]  Enter a new name to create, or existing name to overwrite[/dim]")
        profile_name = typer.prompt(
            "  Profile name",
            default="default",
            show_default=True,
        ).strip()

        username = typer.prompt(f"  {t('setup.prompt_id')}")
        password = getpass.getpass(f"  {t('login.prompt_pass')}")

        console.print(f"[dim]  {t('login.connecting', url=url)}[/dim]")
        try:
            token = get_token(url, username, password)
            save_token(token)
            save_token_for_profile(token, profile_name)
            save_profile_meta(profile_name, moodle_url=url)

            save_creds = typer.confirm(f"  {t('setup.want_save_creds')}", default=True)
            if save_creds:
                save_credentials(username, password, profile_name)
                console.print(f"[green]  {t('login.success_saved')} [profile: {profile_name}][/green]")
            else:
                console.print(f"[green]  {t('login.success')}[/green]")
        except AuthError as e:
            console.print(f"[red]  ✗ {e}[/red]")
            console.print(f"[dim]  {t('setup.login_fail_hint')}[/dim]")
    console.print()

    # Done
    console.print(Panel(
        f"[bold green]{t('setup.done_title')}[/bold green]\n\n{t('setup.done_body')}",
        title="[bold]Ready![/bold]",
        border_style="green",
    ))


@app.callback(invoke_without_command=True)
def setup():
    """Re-run interactive setup wizard."""
    run_setup_wizard()
